import type { Metadata } from "next";
import { Rethink_Sans, Poppins } from "next/font/google";
import "./globals.css";

const rethinkSans = Rethink_Sans({
  variable: "--rethink-sans",
});
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "E Protect Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${rethinkSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
